version : '3'
services:

  weather-app:
    build : ./meteo
    image : meteo:latest
    ports:
      - 80:8080

  remote-weather-app:
    build : ./meteo_services
    image : remote_meteo:latest
    expose :
      - 8080

  admin-ui:
    build : ./actuator_admin
    image : actuator_ui:latest
    ports :
      - 81:8080
