
logging:
  level:
    com.github.benmanes.caffeine.cache: TRACE
    org.springframework.cache: TRACE
    com.pdomingo: TRACE

spring:
  application:
    name: Meteo Service

  cache:
    cache-names: reports
    caffeine:
      spec: maximumSize=500,expireAfterAccess=5m,recordStats
  boot:
      admin:
        url: http://admin-ui:8080

  data:
    mongodb:
      host: mongo
      port: 27017

security:
  basic:
    enabled: false

#----- Actuator Configuration -----#
management:

  server:
    address: 127.0.0.1

  security:
    enabled: false

  endpoints:
      web:
        expose: "*"

  endpoint:
      shutdown:
        enabled: true

#-----------------------------------#

xml:
  context_path: com.pdomingo.entities.soap_xml

remote_ws:
  soap:
    url: http://remote-weather-app:8080/ws
  rest:
    url: http://remote-weather-app:8080/rest/
